name: Fastlane
 
on: [push]
 
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node dependencies
      run: npm install
    - name: Install CocoaPods dependencies
      run: pod install --project-directory=./ios
    - name: Run fastlane setup
      env:
        APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
      run: |
        cd ios
        fastlane setup --verbose
    - name: Run fastlane build
      env:
        APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
      run: |
        fastlane beta --verbose
    - uses: actions/upload-artifact@v2
    - name: Upload artifact
      with:
        name: my-artifact
        path: output/*.ipa