name: Fastlane
 
on: [push]
 
jobs:
  # build-ios:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Install Node dependencies
  #     run: npm install
  #   - name: Install CocoaPods dependencies
  #     run: pod install --project-directory=./ios
  #   - name: Run fastlane setup
  #     env:
  #       APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
  #       TEAM_ID: ${{ secrets.TEAM_ID }}
  #     run: |
  #       cd ios
  #       fastlane beta --verbose
  #   - name: Upload artifact
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: my-artifact
  #       path: output/*.ipa
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install fastlane
      run: sudo gem install fastlane
    - name: Install Node dependencies
      run: npm install
    - name: Generate APK
      run: fastlane android beta
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: android/build/outputs/**/*.apk

